# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_survey', '0002_auto_20170505_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
