# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_survey', '0003_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_survey.University'),
        ),
    ]
