# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_survey', '0004_auto_20170505_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_survey.FeedbackTemplate'),
        ),
    ]
