# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_survey', '0006_section_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionfield',
            name='values',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
