# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_survey', '0008_feedbacktemplate_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktemplate',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
