# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_survey', '0009_auto_20170505_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacktemplate',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
