# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_survey', '0013_feedback_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='state',
            field=models.CharField(choices=[(b'1', b'Pending'), (b'2', b'Completed')], default=1, max_length=3),
        ),
    ]
