# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_survey', '0015_feedback_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
    ]
